# Multi-stage Dockerfile for Render Free Tier with Chrome + Python support
FROM node:18-bullseye AS base

# Install system dependencies for Chrome and Python
RUN apt-get update && apt-get install -y \
    wget \
    gnupg2 \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    xdg-utils \
    python3 \
    python3-pip \
    openssl \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Install Google Chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update \
    && apt-get install -y google-chrome-stable \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages for scrapers
RUN pip3 install --no-cache-dir \
    selenium==4.15.2 \
    undetected-chromedriver==3.5.4 \
    groq==0.4.2 \
    pandas==2.1.4 \
    pyperclip==1.8.2

# Set working directory
WORKDIR /app

# Build arguments for environment variables
ARG DATABASE_URL
ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG OPENAI_API_KEY
ARG OPENAI_ORGANIZATION_ID
ARG OPENAI_CHATBOT_MODEL
ARG OPENAI_CHATBOT_MAX_TOKENS
ARG OPENAI_CHATBOT_TEMPERATURE
ARG OPENAI_CHATBOT_TOP_P
ARG OPENAI_CHATBOT_FREQUENCY_PENALTY
ARG OPENAI_CHATBOT_PRESENCE_PENALTY
ARG CHATBOT_RATE_LIMIT_REQUESTS_PER_MINUTE
ARG CHATBOT_RATE_LIMIT_REQUESTS_PER_HOUR
ARG CHATBOT_RATE_LIMIT_REQUESTS_PER_DAY
ARG CHATBOT_SESSION_TIMEOUT_MINUTES
ARG CHATBOT_MAX_CONVERSATION_HISTORY
ARG CHATBOT_DEFAULT_LANGUAGE
ARG CHATBOT_COST_LIMIT_PER_USER_MONTHLY
ARG CHATBOT_COST_LIMIT_PER_DAY
ARG CHATBOT_ALERT_THRESHOLD_PERCENTAGE
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISHABLE_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG TWITTER_API_KEY
ARG TWITTER_API_SECRET
ARG TWITTER_ACCESS_TOKEN
ARG TWITTER_ACCESS_TOKEN_SECRET
ARG INSTAGRAM_ACCESS_TOKEN
ARG LINKEDIN_ACCESS_TOKEN
ARG GOOGLE_ADS_DEVELOPER_TOKEN
ARG GOOGLE_ADS_CLIENT_ID
ARG GOOGLE_ADS_CLIENT_SECRET
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASS
ARG REDIS_URL
ARG FRONTEND_URL
ARG NODE_ENV
ARG PORT
ARG APP_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CALLBACK_URL
ARG FACEBOOK_APP_ID
ARG FACEBOOK_APP_SECRET
ARG FACEBOOK_CALLBACK_URL
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG GOOGLE_ANALYTICS_ID
ARG FACEBOOK_PIXEL_ID
ARG PAYPAL_CLIENT_ID
ARG PAYPAL_CLIENT_SECRET
ARG ANTHROPIC_API_KEY
ARG AZURE_OPENAI_API_KEY
ARG AZURE_OPENAI_ENDPOINT
ARG SENTRY_DSN
ARG LOG_LEVEL

# Set environment variables
ENV DATABASE_URL=$DATABASE_URL
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRES_IN=$JWT_EXPIRES_IN
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_ORGANIZATION_ID=$OPENAI_ORGANIZATION_ID
ENV OPENAI_CHATBOT_MODEL=$OPENAI_CHATBOT_MODEL
ENV OPENAI_CHATBOT_MAX_TOKENS=$OPENAI_CHATBOT_MAX_TOKENS
ENV OPENAI_CHATBOT_TEMPERATURE=$OPENAI_CHATBOT_TEMPERATURE
ENV OPENAI_CHATBOT_TOP_P=$OPENAI_CHATBOT_TOP_P
ENV OPENAI_CHATBOT_FREQUENCY_PENALTY=$OPENAI_CHATBOT_FREQUENCY_PENALTY
ENV OPENAI_CHATBOT_PRESENCE_PENALTY=$OPENAI_CHATBOT_PRESENCE_PENALTY
ENV CHATBOT_RATE_LIMIT_REQUESTS_PER_MINUTE=$CHATBOT_RATE_LIMIT_REQUESTS_PER_MINUTE
ENV CHATBOT_RATE_LIMIT_REQUESTS_PER_HOUR=$CHATBOT_RATE_LIMIT_REQUESTS_PER_HOUR
ENV CHATBOT_RATE_LIMIT_REQUESTS_PER_DAY=$CHATBOT_RATE_LIMIT_REQUESTS_PER_DAY
ENV CHATBOT_SESSION_TIMEOUT_MINUTES=$CHATBOT_SESSION_TIMEOUT_MINUTES
ENV CHATBOT_MAX_CONVERSATION_HISTORY=$CHATBOT_MAX_CONVERSATION_HISTORY
ENV CHATBOT_DEFAULT_LANGUAGE=$CHATBOT_DEFAULT_LANGUAGE
ENV CHATBOT_COST_LIMIT_PER_USER_MONTHLY=$CHATBOT_COST_LIMIT_PER_USER_MONTHLY
ENV CHATBOT_COST_LIMIT_PER_DAY=$CHATBOT_COST_LIMIT_PER_DAY
ENV CHATBOT_ALERT_THRESHOLD_PERCENTAGE=$CHATBOT_ALERT_THRESHOLD_PERCENTAGE
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET
ENV TWITTER_API_KEY=$TWITTER_API_KEY
ENV TWITTER_API_SECRET=$TWITTER_API_SECRET
ENV TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN
ENV TWITTER_ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET
ENV INSTAGRAM_ACCESS_TOKEN=$INSTAGRAM_ACCESS_TOKEN
ENV LINKEDIN_ACCESS_TOKEN=$LINKEDIN_ACCESS_TOKEN
ENV GOOGLE_ADS_DEVELOPER_TOKEN=$GOOGLE_ADS_DEVELOPER_TOKEN
ENV GOOGLE_ADS_CLIENT_ID=$GOOGLE_ADS_CLIENT_ID
ENV GOOGLE_ADS_CLIENT_SECRET=$GOOGLE_ADS_CLIENT_SECRET
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS
ENV REDIS_URL=$REDIS_URL
ENV FRONTEND_URL=$FRONTEND_URL
ENV NODE_ENV=$NODE_ENV
ENV PORT=$PORT
ENV APP_URL=$APP_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_CALLBACK_URL=$GOOGLE_CALLBACK_URL
ENV FACEBOOK_APP_ID=$FACEBOOK_APP_ID
ENV FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET
ENV FACEBOOK_CALLBACK_URL=$FACEBOOK_CALLBACK_URL
ENV CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
ENV CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
ENV GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID
ENV FACEBOOK_PIXEL_ID=$FACEBOOK_PIXEL_ID
ENV PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
ENV PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET
ENV ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
ENV AZURE_OPENAI_API_KEY=$AZURE_OPENAI_API_KEY
ENV AZURE_OPENAI_ENDPOINT=$AZURE_OPENAI_ENDPOINT
ENV SENTRY_DSN=$SENTRY_DSN
ENV LOG_LEVEL=$LOG_LEVEL

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies
RUN npm ci --only=production && npm cache clean --force

# Generate Prisma Client
RUN npx prisma generate

# Copy application code
COPY . .

# Build the NestJS application
RUN npm run build

# Create directories for uploads and Chrome profile
RUN mkdir -p uploads /tmp/chrome_profile

# Expose port 3001 (Backend default)
EXPOSE 3001

# Health check - uses PORT env or defaults to 3001
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD node -e "require('http').get('http://localhost:${PORT:-3001}/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Start command - run migrations and start server
CMD ["sh", "-c", "npx prisma migrate deploy && node dist/src/main.js"]
